### ISSUE TITLE
I need a **2.28 GIGABYTE** .zip archive folder removed from the Assets/RPGMaker/Storage/System.

### ISSUE THREAD

**Issue by muzudho** [ponta0321/FixRPGMakerUnite#26]
Assets/RPGMaker/Storage/System/Archive folder is 2,456,982,234 bytes (2.28 GB).  
Very **HEAVY**. I want it removed.  

But, reading the RMU source code, the archive is in use.  
I am **FURIOUS**.  

If the official insists that this archive is necessary and cannot be erased, I will have to thoroughly examine the source code to see if it is really necessary and present an alternative.

**Comment by windbellrrr** [comment]
Hello,
From reading the following source, the contents of the Archive folder should only be needed for the first installation from the Unity Asset Store.
Assets\RPGMaker\Codebase\Editor\Common\Helpers\TemplateInstallHelper.cs

In other words, if the zip file in the Archive folder exists under your user folder (*1), you should have no problem deleting the contents of the Archive folder.

*1:
Windows : C:\Users\<User Name>\AppData\LocalLow\.RPGMaker
Mac: /home/<User Name>/.RPGMaker

If you import a new project from the leftmost button of the UNITE tool button (New), the Archive folder will not exist in the newly created project from the beginning.
If the Archive folder is in the way, it may be a good idea to work on a newly created project.

**Comment by muzudho** [comment]
Good morning.
I read a source code.

Files for each country's language are included in the installation.
I see that they are duplicated in the user folder,
It seems that even I, a Japanese person, always check to make sure that the archive files for Chinese and English are included.

I was surprised to find a total of 4.56 GIGABYTE archives in the local PC.
With your advice, it looks like the 2.28 GB file can be erased. 

Thank you very much.
