### ISSUE TITLE
Is it safe to delete `RPG Maker Unite Please Read the Description about Early-Bird Bonus.unitypackage` **(2.25 GB)** file?

### ISSUE THREAD

**Issue by muzudho** [ponta0321/FixRPGMakerUnite#27]
What is this file?  
Is it safe to delete this file?  

`C:\Users\むずでょ\AppData\Roaming\Unity\Asset Store-5.x\Gotcha Gotcha Games\Textures MaterialsGUI Skins\RPG Maker Unite Please Read the Description about Early-Bird Bonus.unitypackage`  

2.25 GB (2,427,186,545 Bytes)

**Comment by walkerjito** [comment]
I am a little unsure about it, It appears to be a plug-in for drawing RMU scene outline diagrams and a package related to the RMU development mode.
I think it is ok to remove it, but it may cause problems when creating a new project.
Also, if you delete it and then re-download or re-install the RPGMakerUnite assets, it will be saved again.

**Comment by muzudho** [comment]
I see! I understood!

This file is my bought.
It was the unity custom package of the RMU.

SAME name
https://assetstore.unity.com/packages/tools/game-toolkits/rpg-maker-unite-please-read-the-description-about-early-bird-bon-253689

Thank you very much!
