### ISSUE TITLE
戦闘中のスプライトによるダメージ表示で数字ダメージの中央位置とMISSの中央位置が異なる

### ISSUE THREAD

**Issue by ponta0321** [ponta0321/FixRPGMakerUnite#28]
v1.00.00:LTS2021.3.16f1
戦闘中のスプライトによるダメージ表示で数字ダメージ表示の中央とMISS表示の中央の位置が異なる
例えば数字ダメージが1000だとすると
&nbsp;&nbsp;&nbsp;1000
MISS
上記のようなズレが生じる。

**Comment by ponta0321** [comment]
v1.00.01:LTS2021.3.16f1
現象再現あり

**Comment by walkerjito** [comment]
SpriteDamage.cs の 247行目の
    _numbers[j].transform.localPosition = new Vector2((j - (4 - 1) / 2) * w, _numbers[j].transform.localPosition.y);

を 
    _numbers[j].transform.localPosition = new Vector2(0, _numbers[j].transform.localPosition.y);

に修正する事で改善しないでしょうか。確認して下さるとありがたいです。

**Comment by ponta0321** [comment]
v1.00.02:LTS2021.3.16f1
バージョンアップにて修正・改善

**Comment by ponta0321** [comment]
v1.00.02:LTS2021.3.16f1
バージョンアップにて修正・改善
